services:
  call_model:
    build:
        context: call_model
        dockerfile: Dockerfile
  generate_yoga:
    build:
        context: generate_yoga
        dockerfile: Dockerfile
    ports:
      - "5001:5000"
  redis:
    image: "redis:alpine"
   
 
